### ISSUE TITLE
Font ligatures make comparison operators page confusing

### ISSUE THREAD

**Issue by andrius4669** [cwida/duckdb-web#3]
`<=`, `>=` and `!=` looks like unicode `≤`, `≥` and `≠`.
consider turning off ligatures or using a font without them.
Now:
![image](https://user-images.githubusercontent.com/4699695/93755915-ddd8c700-fc0c-11ea-87e0-ee0c94828d93.png)
With `font-variant-ligatures: none;`:
![image](https://user-images.githubusercontent.com/4699695/93757361-4de84c80-fc0f-11ea-810f-34182aaee82c.png)

**Comment by Mytherin** [comment]
Great point. Indeed they should be turned off, at the very least for the manual pages. Thanks for opening the issue!

**Comment by hannesmuehleisen** [comment]
CC @jonathanauch

**Comment by hannesmuehleisen** [comment]
This was fixed
